apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blob
  namespace: dss-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-blob
  storageClassName: azureblob-fuse-premium