apiVersion: v1
data:
  allow.textmode: "true"
  color.bad: yellow
  color.good: purple
  enemies: aliens
  enemies.cheat: "true"
  enemies.cheat.level: noGoodRotten
  how.nice.to.look: fairlyNice
  lives: "3"
  secret.code.allowed: "true"
  secret.code.lives: "30"
  secret.code.passphrase: UUDDLRLRBABAS
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-07T08:40:05Z"
  name: dss-cm-env-files
  namespace: dss-apps
  resourceVersion: "774974"
  uid: edc9aa25-e29d-49d1-b9d9-f709649f9557
