---
apiVersion: v1
kind: Namespace
metadata:
  name: dss-apps
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-helloworld-two  
  namespace: dss-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-helloworld-two
  template:
    metadata:
      labels:
        app: aks-helloworld-two
    spec:
      containers:
      - name: aks-helloworld-two
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "AKS app2"
        - name: REPORT_SRV
          value: "Hello from the environment"
        - name: CREATED_BY
          value: "DSS DevOps Admin"
        - name: DB_NAME
          value: "Postgrase & MongoDB"
        - name: DB_HOST
          value: "Some DB details"
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
               name: dss-app2-secret
               key: username
               optional: false 
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dss-app2-secret
              key: password
              optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld-two  
  namespace: dss-apps
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: aks-helloworld-two