apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
  namespace: dss-apps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: azurefile
  resources:
    requests:
      storage: 5Gi