apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blobfuse-new2
  namespace: dss-apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-blobfuse-new
  storageClassName: azureblob-nfs-premium