apiVersion: v1
data:
  azurestorageaccountname: YXp1cmVmaWxlbW91bnRpbmFrcwo=
  azurestorageaccountkey: ck90RlAxTHQzQ2lCSG5Ub2Vaa0l0Q0VPNEtaWXlpenBwMjJkaVFYK1owK3dhYmxDbWRaelowV2tvbmRVTWpUSTgrSkZYM3g4TmQwRCtBU3RuUDhhbmc9PQo=
kind: Secret
metadata:
  name: dss-azfilemount-secret
  namespace: dss-apps
type: Opaque